// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfMonitorBpfCallArgs struct {
	_        structs.HostLayout
	Cmd      uint32
	ProgType uint32
	ProgName [16]int8
}

// loadBpfMonitor returns the embedded CollectionSpec for bpfMonitor.
func loadBpfMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfMonitor: %w", err)
	}

	return spec, err
}

// loadBpfMonitorObjects loads bpfMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfMonitorObjects
//	*bpfMonitorPrograms
//	*bpfMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMonitorSpecs struct {
	bpfMonitorProgramSpecs
	bpfMonitorMapSpecs
	bpfMonitorVariableSpecs
}

// bpfMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMonitorProgramSpecs struct {
	TraceSysEnterBpf *ebpf.ProgramSpec `ebpf:"trace_sys_enter_bpf"`
	TraceSysExitBpf  *ebpf.ProgramSpec `ebpf:"trace_sys_exit_bpf"`
}

// bpfMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMonitorMapSpecs struct {
	BpfArgs       *ebpf.MapSpec `ebpf:"bpf_args"`
	BpfEvents     *ebpf.MapSpec `ebpf:"bpf_events"`
	BpfLostEvents *ebpf.MapSpec `ebpf:"bpf_lost_events"`
	SelfPids      *ebpf.MapSpec `ebpf:"self_pids"`
}

// bpfMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMonitorVariableSpecs struct {
}

// bpfMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMonitorObjects struct {
	bpfMonitorPrograms
	bpfMonitorMaps
	bpfMonitorVariables
}

func (o *bpfMonitorObjects) Close() error {
	return _BpfMonitorClose(
		&o.bpfMonitorPrograms,
		&o.bpfMonitorMaps,
	)
}

// bpfMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMonitorMaps struct {
	BpfArgs       *ebpf.Map `ebpf:"bpf_args"`
	BpfEvents     *ebpf.Map `ebpf:"bpf_events"`
	BpfLostEvents *ebpf.Map `ebpf:"bpf_lost_events"`
	SelfPids      *ebpf.Map `ebpf:"self_pids"`
}

func (m *bpfMonitorMaps) Close() error {
	return _BpfMonitorClose(
		m.BpfArgs,
		m.BpfEvents,
		m.BpfLostEvents,
		m.SelfPids,
	)
}

// bpfMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMonitorVariables struct {
}

// bpfMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMonitorPrograms struct {
	TraceSysEnterBpf *ebpf.Program `ebpf:"trace_sys_enter_bpf"`
	TraceSysExitBpf  *ebpf.Program `ebpf:"trace_sys_exit_bpf"`
}

func (p *bpfMonitorPrograms) Close() error {
	return _BpfMonitorClose(
		p.TraceSysEnterBpf,
		p.TraceSysExitBpf,
	)
}

func _BpfMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfmonitor_bpfel.o
var _BpfMonitorBytes []byte
