// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExecMonitor returns the embedded CollectionSpec for execMonitor.
func loadExecMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execMonitor: %w", err)
	}

	return spec, err
}

// loadExecMonitorObjects loads execMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execMonitorObjects
//	*execMonitorPrograms
//	*execMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execMonitorSpecs struct {
	execMonitorProgramSpecs
	execMonitorMapSpecs
	execMonitorVariableSpecs
}

// execMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execMonitorProgramSpecs struct {
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
}

// execMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execMonitorMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	LostEvents *ebpf.MapSpec `ebpf:"lost_events"`
	SelfPids   *ebpf.MapSpec `ebpf:"self_pids"`
}

// execMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execMonitorVariableSpecs struct {
}

// execMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execMonitorObjects struct {
	execMonitorPrograms
	execMonitorMaps
	execMonitorVariables
}

func (o *execMonitorObjects) Close() error {
	return _ExecMonitorClose(
		&o.execMonitorPrograms,
		&o.execMonitorMaps,
	)
}

// execMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execMonitorMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	LostEvents *ebpf.Map `ebpf:"lost_events"`
	SelfPids   *ebpf.Map `ebpf:"self_pids"`
}

func (m *execMonitorMaps) Close() error {
	return _ExecMonitorClose(
		m.Events,
		m.LostEvents,
		m.SelfPids,
	)
}

// execMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execMonitorVariables struct {
}

// execMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type execMonitorPrograms struct {
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
}

func (p *execMonitorPrograms) Close() error {
	return _ExecMonitorClose(
		p.TraceSchedProcessExec,
	)
}

func _ExecMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execmonitor_bpfel.o
var _ExecMonitorBytes []byte
