// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filetimeMonitorFiletimeArgs struct {
	_           structs.HostLayout
	Filename    [256]int8
	FilenameLen uint32
	Dfd         int32
	Flags       int32
	_           [4]byte
	NewAtime    struct {
		_      structs.HostLayout
		TvSec  int64
		TvNsec int64
	}
	NewMtime struct {
		_      structs.HostLayout
		TvSec  int64
		TvNsec int64
	}
	TimesNull uint8
	_         [7]byte
}

// loadFiletimeMonitor returns the embedded CollectionSpec for filetimeMonitor.
func loadFiletimeMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FiletimeMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filetimeMonitor: %w", err)
	}

	return spec, err
}

// loadFiletimeMonitorObjects loads filetimeMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filetimeMonitorObjects
//	*filetimeMonitorPrograms
//	*filetimeMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFiletimeMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFiletimeMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filetimeMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetimeMonitorSpecs struct {
	filetimeMonitorProgramSpecs
	filetimeMonitorMapSpecs
	filetimeMonitorVariableSpecs
}

// filetimeMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetimeMonitorProgramSpecs struct {
	TraceSysEnterUtimensat *ebpf.ProgramSpec `ebpf:"trace_sys_enter_utimensat"`
	TraceSysExitUtimensat  *ebpf.ProgramSpec `ebpf:"trace_sys_exit_utimensat"`
}

// filetimeMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetimeMonitorMapSpecs struct {
	FiletimeEvents     *ebpf.MapSpec `ebpf:"filetime_events"`
	FiletimeLostEvents *ebpf.MapSpec `ebpf:"filetime_lost_events"`
	SelfPids           *ebpf.MapSpec `ebpf:"self_pids"`
	UtimensatArgs      *ebpf.MapSpec `ebpf:"utimensat_args"`
}

// filetimeMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filetimeMonitorVariableSpecs struct {
}

// filetimeMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFiletimeMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetimeMonitorObjects struct {
	filetimeMonitorPrograms
	filetimeMonitorMaps
	filetimeMonitorVariables
}

func (o *filetimeMonitorObjects) Close() error {
	return _FiletimeMonitorClose(
		&o.filetimeMonitorPrograms,
		&o.filetimeMonitorMaps,
	)
}

// filetimeMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFiletimeMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetimeMonitorMaps struct {
	FiletimeEvents     *ebpf.Map `ebpf:"filetime_events"`
	FiletimeLostEvents *ebpf.Map `ebpf:"filetime_lost_events"`
	SelfPids           *ebpf.Map `ebpf:"self_pids"`
	UtimensatArgs      *ebpf.Map `ebpf:"utimensat_args"`
}

func (m *filetimeMonitorMaps) Close() error {
	return _FiletimeMonitorClose(
		m.FiletimeEvents,
		m.FiletimeLostEvents,
		m.SelfPids,
		m.UtimensatArgs,
	)
}

// filetimeMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFiletimeMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetimeMonitorVariables struct {
}

// filetimeMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFiletimeMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type filetimeMonitorPrograms struct {
	TraceSysEnterUtimensat *ebpf.Program `ebpf:"trace_sys_enter_utimensat"`
	TraceSysExitUtimensat  *ebpf.Program `ebpf:"trace_sys_exit_utimensat"`
}

func (p *filetimeMonitorPrograms) Close() error {
	return _FiletimeMonitorClose(
		p.TraceSysEnterUtimensat,
		p.TraceSysExitUtimensat,
	)
}

func _FiletimeMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filetimemonitor_bpfel.o
var _FiletimeMonitorBytes []byte
