// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fileMonitorFileOpenArgs struct {
	_           structs.HostLayout
	Filename    [256]int8
	FilenameLen uint32
	Flags       uint32
	Dfd         int32
}

// loadFileMonitor returns the embedded CollectionSpec for fileMonitor.
func loadFileMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fileMonitor: %w", err)
	}

	return spec, err
}

// loadFileMonitorObjects loads fileMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileMonitorObjects
//	*fileMonitorPrograms
//	*fileMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFileMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMonitorSpecs struct {
	fileMonitorProgramSpecs
	fileMonitorMapSpecs
	fileMonitorVariableSpecs
}

// fileMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMonitorProgramSpecs struct {
	TraceSysEnterOpenat *ebpf.ProgramSpec `ebpf:"trace_sys_enter_openat"`
	TraceSysExitOpenat  *ebpf.ProgramSpec `ebpf:"trace_sys_exit_openat"`
}

// fileMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMonitorMapSpecs struct {
	FileEvents     *ebpf.MapSpec `ebpf:"file_events"`
	FileLostEvents *ebpf.MapSpec `ebpf:"file_lost_events"`
	OpenatArgs     *ebpf.MapSpec `ebpf:"openat_args"`
	SelfPids       *ebpf.MapSpec `ebpf:"self_pids"`
	WatchedDirs    *ebpf.MapSpec `ebpf:"watched_dirs"`
}

// fileMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMonitorVariableSpecs struct {
}

// fileMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMonitorObjects struct {
	fileMonitorPrograms
	fileMonitorMaps
	fileMonitorVariables
}

func (o *fileMonitorObjects) Close() error {
	return _FileMonitorClose(
		&o.fileMonitorPrograms,
		&o.fileMonitorMaps,
	)
}

// fileMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMonitorMaps struct {
	FileEvents     *ebpf.Map `ebpf:"file_events"`
	FileLostEvents *ebpf.Map `ebpf:"file_lost_events"`
	OpenatArgs     *ebpf.Map `ebpf:"openat_args"`
	SelfPids       *ebpf.Map `ebpf:"self_pids"`
	WatchedDirs    *ebpf.Map `ebpf:"watched_dirs"`
}

func (m *fileMonitorMaps) Close() error {
	return _FileMonitorClose(
		m.FileEvents,
		m.FileLostEvents,
		m.OpenatArgs,
		m.SelfPids,
		m.WatchedDirs,
	)
}

// fileMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMonitorVariables struct {
}

// fileMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMonitorPrograms struct {
	TraceSysEnterOpenat *ebpf.Program `ebpf:"trace_sys_enter_openat"`
	TraceSysExitOpenat  *ebpf.Program `ebpf:"trace_sys_exit_openat"`
}

func (p *fileMonitorPrograms) Close() error {
	return _FileMonitorClose(
		p.TraceSysEnterOpenat,
		p.TraceSysExitOpenat,
	)
}

func _FileMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filemonitor_bpfel.o
var _FileMonitorBytes []byte
