// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadNetMonitor returns the embedded CollectionSpec for netMonitor.
func loadNetMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netMonitor: %w", err)
	}

	return spec, err
}

// loadNetMonitorObjects loads netMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netMonitorObjects
//	*netMonitorPrograms
//	*netMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netMonitorSpecs struct {
	netMonitorProgramSpecs
	netMonitorMapSpecs
	netMonitorVariableSpecs
}

// netMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netMonitorProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
}

// netMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netMonitorMapSpecs struct {
	NetEvents     *ebpf.MapSpec `ebpf:"net_events"`
	NetLostEvents *ebpf.MapSpec `ebpf:"net_lost_events"`
	SelfPids      *ebpf.MapSpec `ebpf:"self_pids"`
}

// netMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netMonitorVariableSpecs struct {
}

// netMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type netMonitorObjects struct {
	netMonitorPrograms
	netMonitorMaps
	netMonitorVariables
}

func (o *netMonitorObjects) Close() error {
	return _NetMonitorClose(
		&o.netMonitorPrograms,
		&o.netMonitorMaps,
	)
}

// netMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type netMonitorMaps struct {
	NetEvents     *ebpf.Map `ebpf:"net_events"`
	NetLostEvents *ebpf.Map `ebpf:"net_lost_events"`
	SelfPids      *ebpf.Map `ebpf:"self_pids"`
}

func (m *netMonitorMaps) Close() error {
	return _NetMonitorClose(
		m.NetEvents,
		m.NetLostEvents,
		m.SelfPids,
	)
}

// netMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type netMonitorVariables struct {
}

// netMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type netMonitorPrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
}

func (p *netMonitorPrograms) Close() error {
	return _NetMonitorClose(
		p.TraceInetSockSetState,
	)
}

func _NetMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netmonitor_bpfel.o
var _NetMonitorBytes []byte
